# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Generate Release Notes
        id: notes
        uses: redcrafter07/release-notes-action@v1.0.1
        with:
          tag-name: "v1.1.0"  # Replace with your actual tag name
          token: ${{ secrets.TEAMS_TOKEN }}
          branch: main
      - name: Print Release Notes
        run: |
          WEBHOOK_URL="https://schneiderelectric.webhook.office.com/webhookb2/446d3a6d-0968-440a-b958-5e6d72a4073a@6e51e1ad-c54b-4b39-b598-0ffe9ae68fef/IncomingWebhook/9555066861fd4424a81b2ec11ea9f7ce/016f5c0f-22ae-4f68-8f3c-5794c1b8702d/V2JjLGH1W7IBfmp2fexP2vcKDcRbW_32RHtRc0-KKCKqo1"
          PAYLOAD=$(cat <<EOF
          {
            "text": "Release info\n
             echo ${{ steps.notes.outputs.release-notes }}"
          }
